import { describe, expect, it } from 'vitest';
import { mergeTags, parseImportedJson } from './importGuests';
import { fullFixture, fullFixtureJson } from './testFixtures';
import type { Guest, TableTag } from '../types';

/** Look a guest up by first name — ids are regenerated by some import paths. */
function byName(guests: Guest[], name: string): Guest {
  const found = guests.find((g) => g.name === name);
  if (!found) throw new Error(`no guest named ${name}`);
  return found;
}

describe('parseImportedJson — GuestSeat export round-trip (shape 3)', () => {
  it('brings back every guest field the exporter wrote', () => {
    const original = fullFixture();
    const result = parseImportedJson(fullFixtureJson());

    // The exporter writes the whole EventState, so the importer must read the whole thing back.
    expect(result.guests).toEqual(original.guests);
    expect(result.tables).toEqual(original.tables);
    expect(result.tags).toEqual(original.tags);
    expect(result.details).toEqual(original.details);
    expect(result.eventName).toBe(original.eventName);
  });

  it('keeps table shape, side, tags and seating', () => {
    const result = parseImportedJson(fullFixtureJson());
    const long = result.tables.find((t) => t.id === 't2')!;
    expect(long.shape).toBe('long');
    expect(long.side).toBe('groom');
    expect(long.tagIds).toEqual(['tag1', 'tag2']);
    expect(byName(result.guests, 'Elira').tableId).toBe('t1');
  });

  it('drops references that cannot resolve inside the file', () => {
    const raw = fullFixtureJson() as any;
    raw.guests[0].tagIds = ['tag1', 'ghost-tag'];
    raw.guests[0].linkedGuestIds = ['g2', 'ghost-guest'];
    raw.guests[0].apartGuestIds = ['ghost-guest'];
    raw.guests[0].tableId = 'ghost-table';

    const guest = byName(parseImportedJson(raw).guests, 'Elira');
    expect(guest.tagIds).toEqual(['tag1']);
    expect(guest.linkedGuestIds).toEqual(['g2']);
    expect(guest.apartGuestIds).toBeUndefined();
    expect(guest.tableId).toBeNull();
  });

  it('rejects wrongly-typed fields instead of storing them', () => {
    const raw = fullFixtureJson() as any;
    raw.guests[0].rsvp = 'maybe';
    raw.guests[0].meal = 42;
    raw.guests[0].arrived = 'yes';
    raw.guests[0].notes = { text: 'nope' };
    raw.guests[0].tagIds = 'tag1';
    raw.tables[0].capacity = -3;
    raw.tables[1].shape = 'triangle';
    raw.details.eventType = 'coronation';
    raw.details.invitationTemplate = 'neon';
    raw.details.agenda = [{ id: 'a1', time: '17:30' }, 'not an item'];

    const result = parseImportedJson(raw);
    const guest = byName(result.guests, 'Elira');
    expect(guest.rsvp).toBeUndefined();
    expect(guest.meal).toBeUndefined();
    expect(guest.arrived).toBeUndefined();
    expect(guest.notes).toBeUndefined();
    expect(guest.tagIds).toBeUndefined();
    expect(result.tables[0].capacity).toBe(8); // fell back to the default
    expect(result.tables[1].shape).toBeUndefined();
    expect(result.details?.eventType).toBeUndefined();
    expect(result.details?.invitationTemplate).toBeUndefined();
    expect(result.details?.agenda).toBeUndefined(); // an item without a title isn't a schedule line
  });

  it('gives colliding or missing tag ids a fresh id', () => {
    const raw = {
      guests: [{ name: 'Ana', tagIds: ['dup'] }],
      tags: [
        { id: 'dup', label: 'First', color: 'rose' },
        { id: 'dup', label: 'Second', color: 'sky' },
        { label: 'No id', color: 'teal' },
        { id: 'bad-color', label: 'Odd', color: 'chartreuse' },
        { id: 'no-label' },
      ],
    };
    const result = parseImportedJson(raw);
    expect(result.tags).toHaveLength(4); // the label-less tag is skipped
    expect(new Set(result.tags!.map((t) => t.id)).size).toBe(4);
    expect(result.tags!.find((t) => t.label === 'Odd')!.color).toBe('slate');
    // Only the first tag keeps the shared id, so that is the one the guest still points at.
    expect(result.guests[0].tagIds).toEqual(['dup']);
  });

  it('throws when the file has no usable guests', () => {
    expect(() => parseImportedJson({ guests: [{ surname: 'Only surname' }] })).toThrow();
    expect(() => parseImportedJson('not an object')).toThrow();
    expect(() => parseImportedJson([])).toThrow();
    expect(() => parseImportedJson({ something: 'else' })).toThrow();
  });
});

describe('parseImportedJson — plainer shapes', () => {
  it('seats a grouped list at one table per key', () => {
    const result = parseImportedJson({ A: ['Ana', 'Beni'], B: ['Cimi'] }, 'Table');
    expect(result.tables.map((t) => t.name)).toEqual(['Table A', 'Table B']);
    expect(result.tables[0].capacity).toBe(2);
    expect(byName(result.guests, 'Ana').tableId).toBe(result.tables[0].id);
    expect(byName(result.guests, 'Ana').group).toBe('A');
  });

  it('numbers tables instead of lettering them when asked', () => {
    const result = parseImportedJson({ A: ['Ana'], B: ['Beni'] }, 'Tavolina', 'numbers');
    expect(result.tables.map((t) => t.name)).toEqual(['Tavolina 1', 'Tavolina 2']);
  });

  it('leaves a flat array unseated and strips tags it cannot resolve', () => {
    const result = parseImportedJson([' Ana ', { name: 'Beni', tagIds: ['x'] }, '', 5 as never]);
    expect(result.guests.map((g) => g.name)).toEqual(['Ana', 'Beni']);
    expect(result.guests.every((g) => g.tableId === null)).toBe(true);
    expect(result.guests[1].tagIds).toBeUndefined();
    expect(result.tags).toBeUndefined();
  });
});

describe('mergeTags', () => {
  const rose: TableTag = { id: 'tag1', label: "Bride's family", color: 'rose' };

  it('reuses a tag that is already there under the same id', () => {
    const merged = mergeTags([rose], [{ ...rose }], [], []);
    expect(merged.tags).toEqual([rose]);
  });

  it('appends tags whose ids are free', () => {
    const merged = mergeTags([rose], [{ id: 'tag9', label: 'Neighbours', color: 'teal' }], [], []);
    expect(merged.tags.map((t) => t.label)).toEqual(["Bride's family", 'Neighbours']);
  });

  it('re-ids a colliding tag and rewrites the references to it', () => {
    const incoming: TableTag = { id: 'tag1', label: 'Work friends', color: 'sky' };
    const guests: Guest[] = [{ id: 'g1', name: 'Ana', tableId: null, tagIds: ['tag1'] }];
    const tables = [{ id: 't1', name: 'A', capacity: 4, tagIds: ['tag1'] }];

    const merged = mergeTags([rose], [incoming], guests, tables);
    const workFriends = merged.tags.find((t) => t.label === 'Work friends')!;
    expect(workFriends.id).not.toBe('tag1');
    expect(merged.guests[0].tagIds).toEqual([workFriends.id]);
    expect(merged.tables[0].tagIds).toEqual([workFriends.id]);
    // The tag that was already open keeps its id, so its own guests are untouched.
    expect(merged.tags.find((t) => t.id === 'tag1')).toEqual(rose);
  });

  it('folds a colliding tag into an identical one instead of duplicating it', () => {
    const base: TableTag[] = [
      { id: 'a', label: 'Cousins', color: 'rose' },
      { id: 'b', label: 'Work friends', color: 'sky' },
    ];
    const guests: Guest[] = [{ id: 'g1', name: 'Ana', tableId: null, tagIds: ['a'] }];
    // Same id as "Cousins", but really the same tag as "Work friends".
    const merged = mergeTags(base, [{ id: 'a', label: 'Work friends', color: 'sky' }], guests, []);
    expect(merged.tags).toHaveLength(2);
    expect(merged.guests[0].tagIds).toEqual(['b']);
  });
});
